spring.application.name=Aula15
spring.datasource.url= jdbc:mysql://localhost:3306/BDAula01?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=laboratorio
spring.jpa.hibernate.ddl-auto=update
