/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author laboratorio
 */
public class MercadoMenu extends javax.swing.JFrame {

    /**
     * Creates new form MercadoMenu
     */
    public MercadoMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PagCadastro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PagConsulta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        PagConsulta1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        pagInfo = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Mercado");

        jMenu1.setText("Cadastrar Produto");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        PagCadastro.setText("Pagina de Cadastro");
        PagCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(PagCadastro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("    Consultar Produtos    ");

        PagConsulta.setText("Pagina de Consulta");
        PagConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(PagConsulta);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("  Serviços   ");

        PagConsulta1.setText("Consulta Remota");
        PagConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagConsulta1ActionPerformed(evt);
            }
        });
        jMenu5.add(PagConsulta1);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ajuda");

        pagInfo.setText("Informaçoes");
        pagInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagInfoActionPerformed(evt);
            }
        });
        jMenu6.add(pagInfo);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void PagConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagConsultaActionPerformed
            ConsultaProdutos consultaProdutos = new ConsultaProdutos();
            consultaProdutos.setVisible(true);
    }//GEN-LAST:event_PagConsultaActionPerformed

    private void PagCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagCadastroActionPerformed
            CadastroProdutos cadProdutos = new CadastroProdutos();
            cadProdutos.setVisible(true);
    }//GEN-LAST:event_PagCadastroActionPerformed

    private void PagConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagConsulta1ActionPerformed
        ConsultaRemota remota = new ConsultaRemota();
        remota.setVisible(true);
    }//GEN-LAST:event_PagConsulta1ActionPerformed

    private void pagInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagInfoActionPerformed
       Informacoes info = new Informacoes();
       info.setVisible(true);
    }//GEN-LAST:event_pagInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MercadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MercadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MercadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MercadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MercadoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PagCadastro;
    private javax.swing.JMenuItem PagConsulta;
    private javax.swing.JMenuItem PagConsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem pagInfo;
    // End of variables declaration//GEN-END:variables
}
